### ISSUE TITLE
Faire Punkteberechnung. 

### ISSUE THREAD

**Issue by sigmea94** [martilidad/whereami_server#2]

**Comment by martilidad** [comment]
Map größe ist mir hier nicht so wichtig. Es muss aber eine stetige Funktion sein, die nicht wegen ein paar meter differenz abstuft. Am besten eine Exponentialfunktion um die Mapgröße verschoben ist.

**Comment by sigmea94** [comment]
Die Punkteberechnung wurde auf eine Konfigurierbare Exponential-Funktion umgestellt. Ich bin allerdings noch nicht ganz zufrieden, da die Funktion am Ende sehr flach verläuft.

**Comment by martilidad** [comment]
warscheinlich solte man eh mindestens die southwest und northeast koordinaten bei der gameerstellung mit abspeichern. Damit könnte man die minimap auch automatisch auf diese Bounds festlegen.

**Comment by martilidad** [comment]
es werden jetzt feste bounds für jedes game berechnet, diese könnten noch in die punkteberechnung mit einfließen

**Comment by sigmea94** [comment]
Vermutlich sollte einfach bei der Game-Erstellung die lastPointDistance (app.js) optional manuell konfiguriert werden können. Die Punkte nur auf die Mapgröße zu beschränken halte ich für nicht sinnvoll, da z.B. auch die Schwierigkeit der Orte Einfluss darauf haben sollten.
Für bessere usability könnten dafür auch feste Kategorien definiert werden (verschiedene Größenstufen und Schwierigkeitsgrade)

**Comment by martilidad** [comment]
closed after angular merge

**Comment by sigmea94** [comment]
warum wurde das geschlossen? Die Punkteberechnung ist doch noch immer nicht von der Größe des Games abhängig.

**Comment by martilidad** [comment]
Punkteberechnung ist fair, sry hätte die kommentare lesen können. Folgeticket: https://github.com/martilidad/whereami_server/issues/61
