### ISSUE TITLE
Game-Erstellung, Bereich genauer definieren

### ISSUE THREAD

**Issue by sigmea94** [martilidad/whereami_server#6]
Statt einem Rechteck bei der Map-Erstellung sollte es möglich sein einen Bereich genauer zu definieren.
z.B. mit https://developers.google.com/maps/documentation/javascript/examples/drawing-tools

**Comment by martilidad** [comment]
Die funktionalität wurde  hier bereits implementiert, die funktion calculateEventArea(event) muss aber noch um die korrekte berechnung für kreise und polygone erweitert werden. (für die gewichtung des random generators)
